#!/usr/bin/env python3
"""Generate the Gazebo world containing a ray-visible 5 cm soil-column proxy."""

from __future__ import annotations

import argparse
import math
from pathlib import Path


DOMAIN_MIN_M = 0.0
CELL_SIZE_M = 0.05
SLICE_WIDTH_M = 2.7
PILE_CENTER_M = 7.0
PILE_HEIGHT_M = 1.8
ANGLE_OF_REPOSE_DEG = 34.0
COLUMN_HEIGHT_M = 1.8


def height_at(index: int) -> float:
    x = DOMAIN_MIN_M + (index + 0.5) * CELL_SIZE_M
    slope = math.tan(math.radians(ANGLE_OF_REPOSE_DEG))
    return max(0.0, PILE_HEIGHT_M - slope * abs(x - PILE_CENTER_M))


def column_model(index: int, height: float) -> str:
    x = DOMAIN_MIN_M + (index + 0.5) * CELL_SIZE_M
    z = height - 0.5 * COLUMN_HEIGHT_M
    return f"""
    <model name="soil_column_{index:03d}">
      <static>true</static>
      <pose>{x:.6f} 0 {z:.6f} 0 0 0</pose>
      <link name="link">
        <visual name="visual">
          <geometry><box><size>{CELL_SIZE_M:.6f} {SLICE_WIDTH_M:.6f} {COLUMN_HEIGHT_M:.6f}</size></box></geometry>
          <material>
            <ambient>0.58 0.38 0.18 1</ambient>
            <diffuse>0.72 0.50 0.25 1</diffuse>
          </material>
        </visual>
      </link>
    </model>"""


def render_world(*, observer_lidar: bool, sensor_systems: bool) -> str:
    columns = []
    for index in range(280):
        height = height_at(index)
        columns.append(column_model(index, height))
    column_text = "".join(columns)
    sensor_plugins = """
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>""" \
        if observer_lidar or sensor_systems else ""
    observer_model = """
    <model name="soil_observer_lidar">
      <static>true</static>
      <pose>5.3 -7.0 2.5 0 0 1.570796327</pose>
      <link name="link">
        <sensor name="gpu_lidar" type="gpu_lidar">
          <always_on>true</always_on>
          <update_rate>10</update_rate>
          <visualize>false</visualize>
          <topic>/loader_soil/observer/scan</topic>
          <lidar>
            <scan>
              <horizontal>
                <samples>512</samples><resolution>1</resolution>
                <min_angle>-0.50</min_angle><max_angle>0.50</max_angle>
              </horizontal>
              <vertical>
                <samples>32</samples><resolution>1</resolution>
                <min_angle>-0.45</min_angle><max_angle>0.10</max_angle>
              </vertical>
            </scan>
            <range><min>0.5</min><max>20.0</max><resolution>0.01</resolution></range>
          </lidar>
        </sensor>
      </link>
    </model>
""" if observer_lidar else ""
    return f"""<?xml version="1.0"?>
<!-- Generated by tools/soil_slice/generate_soil_proxy_world.py. -->
<sdf version="1.10">
  <world name="loader_soil_slice">
    <physics name="loader_500hz" type="dart">
      <max_step_size>0.002</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
{sensor_plugins}
    <gravity>0 0 -9.80665</gravity>

    <light name="sun" type="directional">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.8 0.8 0.8 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>-0.5 0.2 -1</direction>
    </light>

    <model name="rigid_ground">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>80 40</size></plane></geometry>
          <surface><contact><collide_bitmask>0x01</collide_bitmask></contact></surface>
        </collision>
        <visual name="visual">
          <geometry><plane><normal>0 0 1</normal><size>80 40</size></plane></geometry>
          <material><diffuse>0.30 0.27 0.22 1</diffuse></material>
        </visual>
      </link>
    </model>

    <!--
      Each 5 cm column is a constant-height box whose top follows the analytic
      height field; unused length remains below the rigid ground.  The columns
      are visual / GPU-lidar geometry only: analytic soil forces own contact.
    -->{column_text}
{observer_model}
  </world>
</sdf>
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    parser.add_argument("--observer-lidar", action="store_true")
    parser.add_argument("--sensor-systems", action="store_true")
    args = parser.parse_args()
    args.output.write_text(
        render_world(
            observer_lidar=args.observer_lidar,
            sensor_systems=args.sensor_systems,
        ),
        encoding="utf-8",
        newline="\n",
    )
    column_count = 280
    print(f"generated {args.output} with {column_count} soil columns")


if __name__ == "__main__":
    main()
